### ISSUE TITLE
org.apache.spark.SparkException: Task failed while writing rows.  

### ISSUE THREAD

**Issue by cfregly** [linkedin/spark-tfrecord#2] opened 2020-05-14 04:08 UTC
Spark 2.4.5, writing to S3, using s3a://

Any idea how to avoid the failing (and slow) writes using this spark-tfrecord library with S3?

```
04:00:20
2020-05-14 04:00:20,254 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 7.0 (TID 8, algo-2, executor 1): org.apache.spark.SparkException: Task failed while writing rows.
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
04:00:20
#011at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
04:00:20
#011at org.apache.spark.scheduler.Task.run(Task.scala:123)
04:00:20
#011at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
04:00:20
#011at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
04:00:20
#011at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
04:00:20
#011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
04:00:20
#011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
04:00:20
#011at java.lang.Thread.run(Thread.java:748)
04:00:20
Caused by: java.io.IOException: Filesystem {bucket=sagemaker-us-east-1-835319576252, key='amazon-reviews-spark-processor-2020-05-14-03-47-27/output/bert-train/_temporary/0/_temporary/attempt_20200514035207_0007_m_000001_8/part-00001-c880f242-8058-4a00-b2cd-ea2b7972584b-c000.tfrecord'} closed
04:00:20
#011at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.checkOpen(S3ABlockOutputStream.java:224)
04:00:20
#011at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.flush(S3ABlockOutputStream.java:236)
04:00:20
#011at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
04:00:20
#011at java.io.DataOutputStream.flush(DataOutputStream.java:123)
04:00:20
#011at java.io.DataOutputStream.flush(DataOutputStream.java:123)
04:00:20
#011at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
04:00:20
#011at com.linkedin.spark.datasources.tfrecord.TFRecordOutputWriter.close(TFRecordOutputWriter.scala:40)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:57)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:74)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:247)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:242)
04:00:20
#011at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
04:00:20
#011at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
04:00:20
#011... 10 more
```

**Comment by cfregly** [comment] 2020-05-14 15:31
@junshi15 ^^

**Comment by junshi15** [comment] 2020-05-14 15:45
I assume you re-compiled the code with spark 2.4.5, so there is no version conflict.
As a sanity check, I assume it worked on your local filesystem and maybe other HDFS systems. I don't have any experience with s3a . We use it mostly in our internal HDFS systems and have not seen an issue. Spark-TFRecord uses generic hadoop hdfs i/o from tensorflow-hadoop. I don't know if we need to handle s3a in a particular way.

**Comment by junshi15** [comment] 2020-05-14 15:54
The error is due to Filesystem closed
Caused by: java.io.IOException: Filesystem {bucket=sagemaker-us-east-1-835319576252, key='amazon-reviews-spark-processor-2020-05-14-03-47-27/output/bert-train/_temporary/0/_temporary/attempt_20200514035207_0007_m_000001_8/part-00001-c880f242-8058-4a00-b2cd-ea2b7972584b-c000.tfrecord'} closed
My wild guess: is this related to s3a file system security setting?

**Comment by cfregly** [comment] 2020-05-14 17:33
yes, i recompiled with spark 2.4.5.

this is an age-old issue of writing that _temporary/ directory to object storage like S3.  

the workaround is usually to use s3a (which i am) and a couple other hadoop-specific  things (which i've already tried.)

ok, so you're using internal HDFS and therefore haven't seen this.  this will require some hacking.

**Comment by junshi15** [comment] 2020-05-14 18:52
Sorry, I don't use s3a. Don't know how to help you.

**Comment by echan5** [comment] 2020-06-23 18:50
@cfregly just wondering if you ever ended up getting this to work? I'm having the same error with it writing out to a _temporary directory on s3 but then getting the file closed error. Running the same script using the Spark-Tensorflow-connector works successfully (but I'd love to leverage the partitionBy capabilities of Spark-TFRecord)

-using spark 2.3.2
-using s3a

**Comment by cfregly** [comment] 2020-06-24 03:21
I have not found a solution, no.  I just stopped using this library, unfortunately.

@junshi15 a lot of people use s3.  Can you help us find a workaround?

**Comment by junshi15** [comment] 2020-06-25 08:01
@cfregly You mentioned this is an old problem, does it happen to other format as well, parquet, avro, etc.?
If you can show me how this issue is resolved for other formats, I can take a look.
But without any experience with S3, it will be hard for me to even verify the workaround, even if I come up with one.

**Comment by echan5** [comment] 2020-06-25 13:49
I'm not sure how much this helps (and I don't know the details of how exactly it works under the hood), but I've had success writing out to S3 using the parquet format when using EMR, I think because it can use an "S3 optimized committer" for parquet (in this case, with EMR, I'm using the EMRFS file system and not S3A): https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-s3-optimized-committer.html

For Hadoop 3.1 and later (which unfortunately I don't have access to so I haven't been able to try it out), there is also supposed to be an optimized "S3A Committer" https://hadoop.apache.org/docs/r3.1.1/hadoop-aws/tools/hadoop-aws/committers.html 

I believe the main problem that these optimized committers try to address is that in the old implementation, when writing out, Hadoop initially writes out to a "_temporary" directory, then renames those files once the job is officially committed. This approach may be fine if writing out locally but problematic when a bunch of connections need to be made with S3. 

This very old bug task also describes this problem: https://issues.apache.org/jira/browse/SPARK-2984

This is at least my very rough understanding of the problem.

**Comment by echan5** [comment] 2020-06-25 23:08
Actually, I seem to have this working successfully on EMR now. I've tinkered around with settings, versions and recompiling so I'm not exactly which of those changes ultimately made it work but I am using emr-5.24.0 (which uses Hadoop 2.8.5 and Spark 2.4.2). I was originally on Spark 2.3 on my own ec2 instance when I built Spark-TFRecord, and then passing the spark-tfrecord_2.11-0.1.1.jar file to EMR, so that was probably the reason it was not working on EMR originally due to a version conflict. Although I still can't get it to work on my own ec2 instance (may be due to version conflicts as well), as long as it's working on EMR, I'll take it for now! Thanks for the discussion!

**Comment by echan5** [comment] 2020-06-25 23:53
One more update in case this helps - finally got it working on my own ec2 instance after upgrading from hadoop 3.0 to 3.2.0 (and on pyspark 2.4.6). I did get this warning and I'm not sure if it will be problematic down the road (I just ran a test on a small set of files)
```
2020-06-25 23:41:25,812 WARN commit.AbstractS3ACommitterFactory: Using standard FileOutputCommitter to commit work. This is slow and potentially unsafe.
2020-06-25 23:41:25,812 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
```

**Comment by junshi15** [comment] 2020-06-26 05:00
@echan5 Thanks for sharing your experience.

**Comment by cfregly** [comment] 2020-06-26 05:17
I tested hadoop 3.2.1 with spark 2.4.6 just now - and it worked!

Thanks @echan5 for inspiring me to “Upgrade and Pray.”  Haha.

It’s extremely slow (40 mins for 200,000 records), but at least it didn’t fail.  Next step will be to figure out my bottleneck.  It’s related to the combination of the output writer and s3, for sure.  I know Netflix has done some work in this area over the last couple years.  I’ll search around and try some things.

While thr same operation is much faster with straight TensorFlow/Keras 2.x and python (3-4 minutes for 200,000 records), it’s nice to know that Spark-TFRecord is an option.

**Comment by junshi15** [comment] 2020-07-14 22:30
It seems hadoop 3.2.1 and spark 2.4.6 solve this issue. Close the issue.

**Closed as completed by junshi15** 2020-07-14 22:30 UTC

**Comment by cfregly** [comment] 2020-07-15 01:09
it's too slow to be usable, unfortunately.  

the tensorflow/ecosystem option is also too slow, so i've gone a different direction entirely.  

@echan5 how is performance for you?

**Comment by echan5** [comment] 2020-07-15 15:11
@cfregly performance has been adequate enough for me. I typically run on EMR with bigger data volumes, but for a test run with a much smaller sample dataset on a standalone ec2 instance, it looks like it took about 45 seconds to write ~47k records (~155 MB) to s3 using s3a, in case that helps with a rough idea of performance at my end.
